name: meta-marker-count
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - bash
  - coreutils
  - curl
  - findutils
  - gawk
  - grep
  - gzip
  - r-base
  - r-ggplot2
  - r-igraph
  - r-vegan
  - sed
  - seqkit
  - bbmap
  - minimap2
